### ISSUE TITLE
Time column creation not working

### ISSUE THREAD

**Issue by jacobpwagner** [jmeskas/flowCut#4]
Hi @jmeskas.

I'm running into an issue with files that don't have an included time channel. Specifically, [this block](https://github.com/jmeskas/flowCut/blob/7ad0afd1291be037ed4e2b6ec40df3dd7298aa9e/R/flowCut.R#L336-L356) is meant to handle this situation, but I am getting an error from the expression matrix replacement on [this line](https://github.com/jmeskas/flowCut/blob/7ad0afd1291be037ed4e2b6ec40df3dd7298aa9e/R/flowCut.R#L340):

```
Error: the following parameters are not defined in the 'flowFame' object:
	
unable to replace
```

The same will happen even if you name the column before replacement, e.g. this:
```
exprs(f) <- cbind(exprs(f), Time=seq_len(nrow(f)))
```
yields this error
```
Error: the following parameters are not defined in the 'flowFame' object:
	Time
unable to replace
```
It's curious, because based on the rest of the code in this block it looks like it was working at some point. Anyway, is there a reason you are not using `flowCore::fr_append_cols`, which should take care of this? e.g:
```
time_col <- matrix(seq_len(nrow(f)), ncol=1)
colnames(time_col) <- "Time"
f <- fr_append_cols(f, time_col)
```
I'm also happy to make a PR, but it's a pretty surgical fix in a couple of lines.

Adding a quick reprex using the packaged data:
```
library(flowCut)
data(flowCutData)
no_time <- flowCutData[[1]][,-which(colnames(flowCutData[[1]]) == "Time")]
res_flowCut <- flowCut(no_time, FileID = 1, Plot = "All")
```
yields this error from that block
```
Your data does not have a time channel. flowCut will create one, but now flowCut will not be as fully functional as it could be. Consider recording the time for future projects.
Error: the following parameters are not defined in the 'flowFame' object:
	
unable to replace
```

**Comment by jmeskas-kite** [comment]
Thanks for catching this @jacobpwagner! When flowCut was first created there were many FCS files without a Time channel and this was useful. Nowadays FCS files (almost) always have a time channel and hence I haven't seen this issue. Perhaps something simple was changed. I will have a look at this next week sometime.

**Comment by jmeskas** [comment]
Thanks for catching this @jacobpwagner! When flowCut was first created there were many FCS files without a Time channel and this was useful. Nowadays FCS files (almost) always have a time channel and hence I haven't seen this issue. Perhaps something simple was changed. I will have a look at this next week sometime.

**Comment by jmeskas** [comment]
I see that you gave me a PR. Thank you. I have updated flowCut to 1.5.2 with your changes.
