### ISSUE TITLE
flowCut error - "Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'"

### ISSUE THREAD

**Issue by kathdowd** [jmeskas/flowCut#6]
Hi, 

I keep encountering the error below. However, there is not a "gridsize" option within the function, so do not know how to resolve this error. I tried adjusting the segment size but that did not resolve the issue. I have also been unable to find anything in the documentation regarding grid size. 

_Warning in KernSmooth::bkde2D(x, bandwidth = bandwidth, gridsize = nbin,  :
  Binning grid too coarse for current (small) bandwidth: consider increasing 'gridsize'_

Thanks!

**Comment by jmeskas** [comment]
Hi @kathdowd,

This warning (not an error) occurs when your data has the majority of the events in a small percentage of the range of the data. It comes when creating a plot using the plotDens function for the flowDensity algorithm. Hence this is a flowDensity issue more than a flowCut issue. My advice is to remove all the events that are causing your range to be very large. Or perhaps you have not transformed your data and all your events are congregated around the origin. If you are still having issues, please post a reproducible example. 

Thank you,
Justin
